=begin comment

Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.14.6

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Kubernetes::Object::V1ReplicaSetStatus;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Kubernetes::Object::V1ReplicaSetCondition;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#ReplicaSetStatus represents the current status of a ReplicaSet.
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.14.6

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new { 
    my ($class, %args) = @_; 

    my $self = bless {}, $class;

    $self->init(%args);
    
    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }

    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Kubernetes::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'ReplicaSetStatus represents the current status of a ReplicaSet.',
                                  class => 'V1ReplicaSetStatus',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'available_replicas' => {
        datatype => 'int',
        base_name => 'availableReplicas',
        description => 'The number of available replicas (ready for at least minReadySeconds) for this replica set.',
        format => '',
        read_only => '',
            },
    'conditions' => {
        datatype => 'ARRAY[V1ReplicaSetCondition]',
        base_name => 'conditions',
        description => 'Represents the latest available observations of a replica set&#39;s current state.',
        format => '',
        read_only => '',
            },
    'fully_labeled_replicas' => {
        datatype => 'int',
        base_name => 'fullyLabeledReplicas',
        description => 'The number of pods that have labels matching the labels of the pod template of the replicaset.',
        format => '',
        read_only => '',
            },
    'observed_generation' => {
        datatype => 'int',
        base_name => 'observedGeneration',
        description => 'ObservedGeneration reflects the generation of the most recently observed ReplicaSet.',
        format => '',
        read_only => '',
            },
    'ready_replicas' => {
        datatype => 'int',
        base_name => 'readyReplicas',
        description => 'The number of ready replicas for this replica set.',
        format => '',
        read_only => '',
            },
    'replicas' => {
        datatype => 'int',
        base_name => 'replicas',
        description => 'Replicas is the most recently oberved number of replicas. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'available_replicas' => 'int',
    'conditions' => 'ARRAY[V1ReplicaSetCondition]',
    'fully_labeled_replicas' => 'int',
    'observed_generation' => 'int',
    'ready_replicas' => 'int',
    'replicas' => 'int'
} );

__PACKAGE__->attribute_map( {
    'available_replicas' => 'availableReplicas',
    'conditions' => 'conditions',
    'fully_labeled_replicas' => 'fullyLabeledReplicas',
    'observed_generation' => 'observedGeneration',
    'ready_replicas' => 'readyReplicas',
    'replicas' => 'replicas'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
