=begin comment

Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: v1.13.5

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Kubernetes::Object::V1beta1PodDisruptionBudgetStatus;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");


#
#PodDisruptionBudgetStatus represents information about the status of a PodDisruptionBudget. Status may trail the actual state of a system.
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: v1.13.5

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Kubernetes::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'PodDisruptionBudgetStatus represents information about the status of a PodDisruptionBudget. Status may trail the actual state of a system.',
                                  class => 'V1beta1PodDisruptionBudgetStatus',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'current_healthy' => {
    	datatype => 'int',
    	base_name => 'currentHealthy',
    	description => 'current number of healthy pods',
    	format => '',
    	read_only => '',
    		},
    'desired_healthy' => {
    	datatype => 'int',
    	base_name => 'desiredHealthy',
    	description => 'minimum desired number of healthy pods',
    	format => '',
    	read_only => '',
    		},
    'disrupted_pods' => {
    	datatype => 'HASH[string,DateTime]',
    	base_name => 'disruptedPods',
    	description => 'DisruptedPods contains information about pods whose eviction was processed by the API server eviction subresource handler but has not yet been observed by the PodDisruptionBudget controller. A pod will be in this map from the time when the API server processed the eviction request to the time when the pod is seen by PDB controller as having been marked for deletion (or after a timeout). The key in the map is the name of the pod and the value is the time when the API server processed the eviction request. If the deletion didn&#39;t occur and a pod is still there it will be removed from the list automatically by PodDisruptionBudget controller after some time. If everything goes smooth this map should be empty for the most of the time. Large number of entries in the map may indicate problems with pod deletions.',
    	format => '',
    	read_only => '',
    		},
    'disruptions_allowed' => {
    	datatype => 'int',
    	base_name => 'disruptionsAllowed',
    	description => 'Number of pod disruptions that are currently allowed.',
    	format => '',
    	read_only => '',
    		},
    'expected_pods' => {
    	datatype => 'int',
    	base_name => 'expectedPods',
    	description => 'total number of pods counted by this disruption budget',
    	format => '',
    	read_only => '',
    		},
    'observed_generation' => {
    	datatype => 'int',
    	base_name => 'observedGeneration',
    	description => 'Most recent generation observed when updating this PDB status. PodDisruptionsAllowed and other status informatio is valid only if observedGeneration equals to PDB&#39;s object generation.',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->openapi_types( {
    'current_healthy' => 'int',
    'desired_healthy' => 'int',
    'disrupted_pods' => 'HASH[string,DateTime]',
    'disruptions_allowed' => 'int',
    'expected_pods' => 'int',
    'observed_generation' => 'int'
} );

__PACKAGE__->attribute_map( {
    'current_healthy' => 'currentHealthy',
    'desired_healthy' => 'desiredHealthy',
    'disrupted_pods' => 'disruptedPods',
    'disruptions_allowed' => 'disruptionsAllowed',
    'expected_pods' => 'expectedPods',
    'observed_generation' => 'observedGeneration'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
