=begin comment

Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: v1.13.5

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Kubernetes::Object::V1ISCSIPersistentVolumeSource;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Kubernetes::Object::V1SecretReference;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#ISCSIPersistentVolumeSource represents an ISCSI disk. ISCSI volumes can only be mounted as read/write once. ISCSI volumes support ownership management and SELinux relabeling.
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: v1.13.5

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "Kubernetes::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'ISCSIPersistentVolumeSource represents an ISCSI disk. ISCSI volumes can only be mounted as read/write once. ISCSI volumes support ownership management and SELinux relabeling.',
                                  class => 'V1ISCSIPersistentVolumeSource',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'chap_auth_discovery' => {
    	datatype => 'boolean',
    	base_name => 'chapAuthDiscovery',
    	description => 'whether support iSCSI Discovery CHAP authentication',
    	format => '',
    	read_only => '',
    		},
    'chap_auth_session' => {
    	datatype => 'boolean',
    	base_name => 'chapAuthSession',
    	description => 'whether support iSCSI Session CHAP authentication',
    	format => '',
    	read_only => '',
    		},
    'fs_type' => {
    	datatype => 'string',
    	base_name => 'fsType',
    	description => 'Filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. Implicitly inferred to be \&quot;ext4\&quot; if unspecified. More info: https://kubernetes.io/docs/concepts/storage/volumes#iscsi',
    	format => '',
    	read_only => '',
    		},
    'initiator_name' => {
    	datatype => 'string',
    	base_name => 'initiatorName',
    	description => 'Custom iSCSI Initiator Name. If initiatorName is specified with iscsiInterface simultaneously, new iSCSI interface &lt;target portal&gt;:&lt;volume name&gt; will be created for the connection.',
    	format => '',
    	read_only => '',
    		},
    'iqn' => {
    	datatype => 'string',
    	base_name => 'iqn',
    	description => 'Target iSCSI Qualified Name.',
    	format => '',
    	read_only => '',
    		},
    'iscsi_interface' => {
    	datatype => 'string',
    	base_name => 'iscsiInterface',
    	description => 'iSCSI Interface Name that uses an iSCSI transport. Defaults to &#39;default&#39; (tcp).',
    	format => '',
    	read_only => '',
    		},
    'lun' => {
    	datatype => 'int',
    	base_name => 'lun',
    	description => 'iSCSI Target Lun number.',
    	format => '',
    	read_only => '',
    		},
    'portals' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'portals',
    	description => 'iSCSI Target Portal List. The Portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260).',
    	format => '',
    	read_only => '',
    		},
    'read_only' => {
    	datatype => 'boolean',
    	base_name => 'readOnly',
    	description => 'ReadOnly here will force the ReadOnly setting in VolumeMounts. Defaults to false.',
    	format => '',
    	read_only => '',
    		},
    'secret_ref' => {
    	datatype => 'V1SecretReference',
    	base_name => 'secretRef',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'target_portal' => {
    	datatype => 'string',
    	base_name => 'targetPortal',
    	description => 'iSCSI Target Portal. The Portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260).',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->openapi_types( {
    'chap_auth_discovery' => 'boolean',
    'chap_auth_session' => 'boolean',
    'fs_type' => 'string',
    'initiator_name' => 'string',
    'iqn' => 'string',
    'iscsi_interface' => 'string',
    'lun' => 'int',
    'portals' => 'ARRAY[string]',
    'read_only' => 'boolean',
    'secret_ref' => 'V1SecretReference',
    'target_portal' => 'string'
} );

__PACKAGE__->attribute_map( {
    'chap_auth_discovery' => 'chapAuthDiscovery',
    'chap_auth_session' => 'chapAuthSession',
    'fs_type' => 'fsType',
    'initiator_name' => 'initiatorName',
    'iqn' => 'iqn',
    'iscsi_interface' => 'iscsiInterface',
    'lun' => 'lun',
    'portals' => 'portals',
    'read_only' => 'readOnly',
    'secret_ref' => 'secretRef',
    'target_portal' => 'targetPortal'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
