
=begin comment

Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.13.7

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package Kubernetes::Object::V1ObjectMeta;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use Kubernetes::Object::V1Initializers;
use Kubernetes::Object::V1OwnerReference;

use base ( "Class::Accessor", "Class::Data::Inheritable" );

#
#ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.13.7

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata( 'attribute_map'        => {} );
__PACKAGE__->mk_classdata( 'openapi_types'        => {} );
__PACKAGE__->mk_classdata( 'method_documentation' => {} );
__PACKAGE__->mk_classdata( 'class_documentation'  => {} );

# new plain object
sub new {
    my ( $class, %args ) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init {
    my ( $self, %args ) = @_;

    foreach my $attribute ( keys %{ $self->attribute_map } ) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{$args_key} );
    }
}

# return perl hash
sub to_hash {
    my $self  = shift;
    my $_hash = decode_json( JSON->new->convert_blessed->encode($self) );

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self  = shift;
    my $_data = {};
    foreach my $_key ( keys %{ $self->attribute_map } ) {
        if ( defined $self->{$_key} ) {
            $_data->{ $self->attribute_map->{$_key} } = $self->{$_key};
        }
    }

    return $_data;
}

# from Perl hashref
sub from_hash {
    my ( $self, $hash ) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ( $_key, $_type ) = each %{ $self->openapi_types } ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ( $_type =~ /^array\[(.+)\]$/i ) {    # array
            my $_subclass = $1;
            my @_array    = ();
            foreach my $_element ( @{ $hash->{$_json_attribute} } ) {
                push @_array, $self->_deserialize( $_subclass, $_element );
            }
            $self->{$_key} = \@_array;
        }
        elsif ( $_type =~ /^hash\[string,(.+)\]$/i ) {    # hash
            my $_subclass = $1;
            my %_hash     = ();
            while ( my ( $_key, $_element ) =
                each %{ $hash->{$_json_attribute} } )
            {
                $_hash{$_key} = $self->_deserialize( $_subclass, $_element );
            }
            $self->{$_key} = \%_hash;
        }
        elsif ( exists $hash->{$_json_attribute} )
        {    #hash(model), primitive, datetime
            $self->{$_key} =
              $self->_deserialize( $_type, $hash->{$_json_attribute} );
        }
        else {
            $log->debugf( "Warning: %s (%s) does not exist in input hash\n",
                $_key, $_json_attribute );
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ( $self, $type, $data ) = @_;
    $log->debugf( "deserializing %s with %s", Dumper($data), $type );

    if ( $type eq 'DateTime' ) {
        return DateTime->from_epoch( epoch => str2time($data) );
    }
    elsif ( grep( /^$type$/, ( 'int', 'double', 'string', 'boolean' ) ) ) {
        return $data;
    }
    else {    # hash(model)
        my $_instance = eval "Kubernetes::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}

__PACKAGE__->class_documentation(
    {
        description =>
'ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.',
        class    => 'V1ObjectMeta',
        required => [],               # TODO
    }
);

__PACKAGE__->method_documentation(
    {
        'annotations' => {
            datatype  => 'HASH[string,string]',
            base_name => 'annotations',
            description =>
'Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations',
            format    => '',
            read_only => '',
        },
        'cluster_name' => {
            datatype  => 'string',
            base_name => 'clusterName',
            description =>
'The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request.',
            format    => '',
            read_only => '',
        },
        'creation_timestamp' => {
            datatype  => 'DateTime',
            base_name => 'creationTimestamp',
            description =>
'CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.  Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata',
            format    => '',
            read_only => '',
        },
        'deletion_grace_period_seconds' => {
            datatype  => 'int',
            base_name => 'deletionGracePeriodSeconds',
            description =>
'Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.',
            format    => '',
            read_only => '',
        },
        'deletion_timestamp' => {
            datatype  => 'DateTime',
            base_name => 'deletionTimestamp',
            description =>
'DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This field is set by the server when a graceful deletion is requested by the user, and is not directly settable by a client. The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field, once the finalizers list is empty. As long as the finalizers list contains items, deletion is blocked. Once the deletionTimestamp is set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time. For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react by sending a graceful termination signal to the containers in the pod. After that 30 seconds, the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup, remove the pod from the API. In the presence of network partitions, this object may still exist after this timestamp, until an administrator or automated process can determine the resource is fully terminated. If not set, graceful deletion of the object has not been requested.  Populated by the system when a graceful deletion is requested. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata',
            format    => '',
            read_only => '',
        },
        'finalizers' => {
            datatype  => 'ARRAY[string]',
            base_name => 'finalizers',
            description =>
'Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed.',
            format    => '',
            read_only => '',
        },
        'generate_name' => {
            datatype  => 'string',
            base_name => 'generateName',
            description =>
'GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.  If this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).  Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#idempotency',
            format    => '',
            read_only => '',
        },
        'generation' => {
            datatype  => 'int',
            base_name => 'generation',
            description =>
'A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.',
            format    => '',
            read_only => '',
        },
        'initializers' => {
            datatype    => 'V1Initializers',
            base_name   => 'initializers',
            description => '',
            format      => '',
            read_only   => '',
        },
        'labels' => {
            datatype  => 'HASH[string,string]',
            base_name => 'labels',
            description =>
'Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels',
            format    => '',
            read_only => '',
        },
        'name' => {
            datatype  => 'string',
            base_name => 'name',
            description =>
'Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names',
            format    => '',
            read_only => '',
        },
        'namespace' => {
            datatype  => 'string',
            base_name => 'namespace',
            description =>
'Namespace defines the space within each name must be unique. An empty namespace is equivalent to the \&quot;default\&quot; namespace, but \&quot;default\&quot; is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.  Must be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces',
            format    => '',
            read_only => '',
        },
        'owner_references' => {
            datatype  => 'ARRAY[V1OwnerReference]',
            base_name => 'ownerReferences',
            description =>
'List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.',
            format    => '',
            read_only => '',
        },
        'resource_version' => {
            datatype  => 'string',
            base_name => 'resourceVersion',
            description =>
'An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.  Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency',
            format    => '',
            read_only => '',
        },
        'self_link' => {
            datatype  => 'string',
            base_name => 'selfLink',
            description =>
'SelfLink is a URL representing this object. Populated by the system. Read-only.',
            format    => '',
            read_only => '',
        },
        'uid' => {
            datatype  => 'string',
            base_name => 'uid',
            description =>
'UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.  Populated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids',
            format    => '',
            read_only => '',
        },
    }
);

__PACKAGE__->openapi_types(
    {
        'annotations'                   => 'HASH[string,string]',
        'cluster_name'                  => 'string',
        'creation_timestamp'            => 'DateTime',
        'deletion_grace_period_seconds' => 'int',
        'deletion_timestamp'            => 'DateTime',
        'finalizers'                    => 'ARRAY[string]',
        'generate_name'                 => 'string',
        'generation'                    => 'int',
        'initializers'                  => 'V1Initializers',
        'labels'                        => 'HASH[string,string]',
        'name'                          => 'string',
        'namespace'                     => 'string',
        'owner_references'              => 'ARRAY[V1OwnerReference]',
        'resource_version'              => 'string',
        'self_link'                     => 'string',
        'uid'                           => 'string'
    }
);

__PACKAGE__->attribute_map(
    {
        'annotations'                   => 'annotations',
        'cluster_name'                  => 'clusterName',
        'creation_timestamp'            => 'creationTimestamp',
        'deletion_grace_period_seconds' => 'deletionGracePeriodSeconds',
        'deletion_timestamp'            => 'deletionTimestamp',
        'finalizers'                    => 'finalizers',
        'generate_name'                 => 'generateName',
        'generation'                    => 'generation',
        'initializers'                  => 'initializers',
        'labels'                        => 'labels',
        'name'                          => 'name',
        'namespace'                     => 'namespace',
        'owner_references'              => 'ownerReferences',
        'resource_version'              => 'resourceVersion',
        'self_link'                     => 'selfLink',
        'uid'                           => 'uid'
    }
);

__PACKAGE__->mk_accessors( keys %{ __PACKAGE__->attribute_map } );

1;
